os: linux
dist: trusty
language: php

if: tag IS blank

env:
  global:
    - DB_USER=root
    - DB_HOST=localhost
    - DB_NAME=magento2_test
    - ADMIN_FIRSTNAME=admin_firstname
    - ADMIN_LASTNAME=admin_lastname
    - ADMIN_EMAIL=example@email.com
    - ADMIN_USER=admin
    - ADMIN_PASS=admin123

stages:
  - test

jobs:
  include:
    - php: 7.0
      env: BRANCH=2.0.2

    - php: 7.0
      env: BRANCH=2.0.4

    - php: 7.0
      env: BRANCH=2.0.5

    - php: 7.0
      env: BRANCH=2.0.6

    - php: 7.0
      env: BRANCH=2.0.7

    - php: 7.0
      env: BRANCH=2.0.8

    - php: 7.0
      env: BRANCH=2.0.9

    - php: 7.0
      env: BRANCH=2.0.10

    - php: 7.0
      env: BRANCH=2.0.11

    - php: 7.0
      env: BRANCH=2.0.12

    - php: 7.0
      env: BRANCH=2.0.13

    - php: 7.0
      env: BRANCH=2.0.14

    - php: 7.0
      env: BRANCH=2.0.15

    - php: 7.0
      env: BRANCH=2.0.16

    - php: 7.0
      env: BRANCH=2.0.17

    - php: 7.0
      env: BRANCH=2.0.18

    - php: 7.0
      env: BRANCH=2.1.0
    - php: 7.1
      env: BRANCH=2.1.0

    - php: 7.0
      env: BRANCH=2.1.1
    - php: 7.1
      env: BRANCH=2.1.1

    - php: 7.0
      env: BRANCH=2.1.2
    - php: 7.1
      env: BRANCH=2.1.2

    - php: 7.0
      env: BRANCH=2.1.3
    - php: 7.1
      env: BRANCH=2.1.3

    - php: 7.0
      env: BRANCH=2.1.4
    - php: 7.1
      env: BRANCH=2.1.4

    - php: 7.0
      env: BRANCH=2.1.5
    - php: 7.1
      env: BRANCH=2.1.5

    - php: 7.0
      env: BRANCH=2.1.6
    - php: 7.1
      env: BRANCH=2.1.6

    - php: 7.0
      env: BRANCH=2.1.7
    - php: 7.1
      env: BRANCH=2.1.7

    - php: 7.0
      env: BRANCH=2.1.8
    - php: 7.1
      env: BRANCH=2.1.8

    - php: 7.0
      env: BRANCH=2.1.9
    - php: 7.1
      env: BRANCH=2.1.9

    - php: 7.0
      env: BRANCH=2.1.10
    - php: 7.1
      env: BRANCH=2.1.10

    - php: 7.0
      env: BRANCH=2.1.11
    - php: 7.1
      env: BRANCH=2.1.11

    - php: 7.0
      env: BRANCH=2.1.12
    - php: 7.1
      env: BRANCH=2.1.12

    - php: 7.0
      env: BRANCH=2.1.13
    - php: 7.1
      env: BRANCH=2.1.13

    - php: 7.0
      env: BRANCH=2.1.14
    - php: 7.1
      env: BRANCH=2.1.14

    - php: 7.0
      env: BRANCH=2.1.15
    - php: 7.1
      env: BRANCH=2.1.15

    - php: 7.0
      env: BRANCH=2.1.16
    - php: 7.1
      env: BRANCH=2.1.16

    - php: 7.0
      env: BRANCH=2.1.17
    - php: 7.1
      env: BRANCH=2.1.17

    - php: 7.0
      env: BRANCH=2.1.18
    - php: 7.1
      env: BRANCH=2.1.18

    - php: 7.0
      env: BRANCH=2.2.0
    - php: 7.1
      env: BRANCH=2.2.0
    - php: 7.2
      env: BRANCH=2.2.1

    - php: 7.0
      env: BRANCH=2.2.1
    - php: 7.1
      env: BRANCH=2.2.1
    - php: 7.2
      env: BRANCH=2.2.1

    - php: 7.0
      env: BRANCH=2.2.2
    - php: 7.1
      env: BRANCH=2.2.2
    - php: 7.2
      env: BRANCH=2.2.2

    - php: 7.0
      env: BRANCH=2.2.3
    - php: 7.1
      env: BRANCH=2.2.3
    - php: 7.2
      env: BRANCH=2.2.3

    - php: 7.0
      env: BRANCH=2.2.4
    - php: 7.1
      env: BRANCH=2.2.4
    - php: 7.2
      env: BRANCH=2.2.4

    - php: 7.0
      env: BRANCH=2.2.5
    - php: 7.1
      env: BRANCH=2.2.5
    - php: 7.2
      env: BRANCH=2.2.5

    - php: 7.0
      env: BRANCH=2.2.6
    - php: 7.1
      env: BRANCH=2.2.6
    - php: 7.2
      env: BRANCH=2.2.6

    - php: 7.0
      env: BRANCH=2.2.7
    - php: 7.1
      env: BRANCH=2.2.7
    - php: 7.2
      env: BRANCH=2.2.7

    - php: 7.0
      env: BRANCH=2.2.8
    - php: 7.1
      env: BRANCH=2.2.8
    - php: 7.2
      env: BRANCH=2.2.8

    - php: 7.0
      env: BRANCH=2.2.9
    - php: 7.1
      env: BRANCH=2.2.9
    - php: 7.2
      env: BRANCH=2.2.9

    - php: 7.0
      env: BRANCH=2.2.10
    - php: 7.1
      env: BRANCH=2.2.10
    - php: 7.2
      env: BRANCH=2.2.10

    - php: 7.1
      env: BRANCH=2.3.0
    - php: 7.2
      env: BRANCH=2.3.0
    - php: 7.3
      env: BRANCH=2.3.0

    - php: 7.1
      env: BRANCH=2.3.1
    - php: 7.2
      env: BRANCH=2.3.1
    - php: 7.3
      env: BRANCH=2.3.1

    - php: 7.1
      env: BRANCH=2.3.2
    - php: 7.2
      env: BRANCH=2.3.2
    - php: 7.3
      env: BRANCH=2.3.2

    - php: 7.1
      env: BRANCH=2.3.3
    - php: 7.2
      env: BRANCH=2.3.3
    - php: 7.3
      env: BRANCH=2.3.3

    - php: 7.1
      env: BRANCH=2.3.4
    - php: 7.2
      env: BRANCH=2.3.4
    - php: 7.3
      env: BRANCH=2.3.4

before_script:
  - bash bin/install.sh

script: make ci

# deploy:
#  skip_cleanup: true
#  provider: script
#  script: make
#  on:
#    php: 7.2
#    branch: master
#    condition: "$DEPLOY = true"
